// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/test.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserType int32

const (
	UserType_NONE    UserType = 0
	UserType_CAMPUS  UserType = 1
	UserType_VISITOR UserType = 2
)

// Enum value maps for UserType.
var (
	UserType_name = map[int32]string{
		0: "NONE",
		1: "CAMPUS",
		2: "VISITOR",
	}
	UserType_value = map[string]int32{
		"NONE":    0,
		"CAMPUS":  1,
		"VISITOR": 2,
	}
)

func (x UserType) Enum() *UserType {
	p := new(UserType)
	*p = x
	return p
}

func (x UserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_test_proto_enumTypes[0].Descriptor()
}

func (UserType) Type() protoreflect.EnumType {
	return &file_api_test_proto_enumTypes[0]
}

func (x UserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserType.Descriptor instead.
func (UserType) EnumDescriptor() ([]byte, []int) {
	return file_api_test_proto_rawDescGZIP(), []int{0}
}

var file_api_test_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         1108,
		Name:          "api.default_type",
		Tag:           "varint,1108,opt,name=default_type",
		Filename:      "api/test.proto",
	},
}

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional int32 default_type = 1108;
	E_DefaultType = &file_api_test_proto_extTypes[0]
)

var File_api_test_proto protoreflect.FileDescriptor

var file_api_test_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x33, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x43, 0x41, 0x4d, 0x50, 0x55, 0x53, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x56, 0x49, 0x53,
	0x49, 0x54, 0x4f, 0x52, 0x10, 0x02, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x3a, 0x40, 0x0a, 0x0c,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6e, 0x75, 0x6d, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd4, 0x08, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54, 0x79, 0x70, 0x65, 0x42, 0x08,
	0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_test_proto_rawDescOnce sync.Once
	file_api_test_proto_rawDescData = file_api_test_proto_rawDesc
)

func file_api_test_proto_rawDescGZIP() []byte {
	file_api_test_proto_rawDescOnce.Do(func() {
		file_api_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_test_proto_rawDescData)
	})
	return file_api_test_proto_rawDescData
}

var file_api_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_test_proto_goTypes = []interface{}{
	(UserType)(0),                    // 0: api.UserType
	(*descriptorpb.EnumOptions)(nil), // 1: google.protobuf.EnumOptions
}
var file_api_test_proto_depIdxs = []int32{
	1, // 0: api.default_type:extendee -> google.protobuf.EnumOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_test_proto_init() }
func file_api_test_proto_init() {
	if File_api_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_test_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_api_test_proto_goTypes,
		DependencyIndexes: file_api_test_proto_depIdxs,
		EnumInfos:         file_api_test_proto_enumTypes,
		ExtensionInfos:    file_api_test_proto_extTypes,
	}.Build()
	File_api_test_proto = out.File
	file_api_test_proto_rawDesc = nil
	file_api_test_proto_goTypes = nil
	file_api_test_proto_depIdxs = nil
}
